(* ========================================================================= *)
(* Vectors encoded as binary tree dependently typed on the binary            *)
(* representation of finite types.                                           *)
(*                                                                           *)
(* (c) Copyright, Andrea Gabrielli, Marco Maggesi 2017-2018                  *)
(* (c) Copyright, Marco Maggesi 2025                                         *)
(* ========================================================================= *)

loadt "BinTreeVec/binary.ml";;         (* Computing with binary expansions     *)
loadt "BinTreeVec/vector0.ml";;        (* Zero-based vectors                   *)
loadt "BinTreeVec/btvectors.ml";;      (* Binary tree vectors                  *)
needs "BinTreeVec/matrices.ml";;       (* Definitions and lemmata on matrices  *)
loadt "BinTreeVec/real_vector0.ml";;   (* Zero-based real vectors and matrices *)
loadt "BinTreeVec/real_btvectors.ml";; (* Real bintree vectors and matrices    *)
